# -*- coding: utf-8 -*-
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'MathBenTech Enterprise Services for utility business',
    'version': '0.1',
    'author': "MathBenTech",
    'website': 'https://mathben.tech',
    'license': 'AGPL-3',
    'category': 'Other',
    'summary': 'Services for utility business',
    'description': """
MathBenTech Enterprise Services for utility business
====================================================
All modules needed for enterprise with services for utility business.
""",
    'depends': [
        # MathBenTech
        'mathbentech_base_enterprise',

        # Custom MathBenTech
        'product_lump_sum',
        'sale_custom_order_in_lines_and_regroup',
        'sale_margin_percent',
        'sale_product_manufacturer',
        'sale_product_manufacturer_model',

        # OCA sale-workflow
        'sale_order_revision',
        'sale_double_validation',

        # General
        'digest',  # KPI

        # TEST INSTALLS
        'base_comment_template',
        #'sale_comment_template',
        #'purchase_comment_template',
        #'invoice_comment_template',
        'account_invoice_comment_template',
        'partner_time_to_pay',
        'account_invoice_check_total',
        'account_invoice_fixed_discount',
        'account_invoice_force_number',
        'account_invoice_line_description',
        'account_invoice_pricelist',
        'account_invoice_search_by_reference',
        'account_invoice_supplier_ref_unique',
        'account_invoice_supplierinfo_update',
        'account_invoice_tax_required',
        'account_invoice_transmit_method',
        'account_invoice_triple_discount',
        'account_invoice_view_payment',
        'account_payment_term_extension',
        'sale_invoice_line_note',
        'sale_order_invoicing_queued',
        'sale_timesheet_invoice_description',
        'account_due_list',
        'account_due_list_days_overdue',
        'account_payment_credit_card',
        'account_payment_show_invoice',
        'account_banking_reconciliation',
        'account_move_reconcile_helper',
        #'apps_product_creator',  manque github_connector_oca https://github.com/OCA/interface-github
        'account_payment_partner',
        #'bank-statement-import', remplacés par ceux qui suivent
        'account_bank_statement_import_camt_oca',
        'account_bank_statement_import_move_line',
        'account_bank_statement_import_ofx',
        'account_bank_statement_import_paypal',
        'account_bank_statement_import_split',
        'account_brand',
        'brand',
        'contract_brand',
        'partner_brand',
        'product_contract_brand',
        'sale_brand',
        'business_requirement',
        'business_requirement_crm',
        'business_requirement_deliverable',
        'business_requirement_sale',
        'business_requirement_sale_timesheet',
        'sale_commission',
        'sale_commission_formula',
        'sale_commission_pricelist',
        'agreement',
        'agreement_legal',
        'agreement_legal_sale',
        'agreement_project',
        'contract',
        'contract_sale',
        'contract_sale_payment_mode',
        'product_contract',
        'privacy_consent',
        'website_sale_checkout_skip_payment',
        'website_sale_product_attribute_filter_visibility',
        'hr_attendance_modification_tracking',
        'hr_attendance_report_theoretical_time',
        'hr_employee_document',
        'hr_employee_id',
        'hr_employee_service_contract',
        'hr_expense_tier_validation',
        'hr_experience',
        'hr_worked_days_from_timesheet',
        'document_page',
        'document_page_approval',
        'document_page_project',
        'document_url',
        'maintenance_project',
        'maintenance_project_plan',
        'maintenance_timesheet',
        'mrp_bom_component_menu',
        'mrp_bom_location',
        'mrp_bom_tracking',
        'product_replenishment_cost',
        'sale_margin_sync',
        'mis_builder',
        'mis_builder_budget',
        'muk_attachment_lobject',
        'muk_branding',
        'muk_converter',
        'muk_web_theme',
        'base_location',
        'base_location_nuts',
        'partner_affiliate',
        'partner_capital',
        'partner_company_group',
        'partner_contact_personal_information_page',
        'partner_external_map',
        'partner_fax',
        'partner_identification',
        'partner_industry_secondary',
        'partner_phonecall_schedule',
        'partner_second_lastname',
        #'product_attribute', à analyser les modules, à revoir selon les besoins de noxe du 4 février 2020
        'project_deadline',
        'project_hr',
        'project_list',
        'project_milestone',
        'project_status',
        'project_tag',
        'project_task_dependency',
        'project_task_material',
        'project_task_project_required',
        'project_wbs',
        'purchase_commercial_partner',
        'purchase_deposit',
        'purchase_discount',
        'purchase_last_price_info',
        'purchase_order_archive',
        'purchase_order_line_description',
        'purchase_quick',
        'purchase_request_tier_validation',
        'purchase_requisition_tier_validation',
        'purchase_tier_validation',
        'subcontracted_service',
        'quotation_revision',
        #'reporting-engine', c'est un repo, à analyser
        #'kpi', a besoin de base_external_dbsource
        'report_xlsx',
        'report_xlsx_helper',
        #'sale-workflow', C'est un repo
        'partner_prospect',
        'sale_automatic_workflow_payment_mode',
        'sale_cancel_reason',
        'sale_discount_display_amount',
        'sale_double_validation',
        'sale_fixed_discount',
        'sale_invoice_group_method',
        'sale_invoice_plan',
        'sale_last_price_info',
        'sale_order_archive',
        'sale_order_digitized_signature',
        'sale_order_line_description',
        'sale_order_line_input',
        'sale_order_revision',
        'sale_product_multi_add',
        'sale_product_set',
        #'password_security', needs: zxcvbn
        'base_technical_user',
        #'excel_import_export', needs: No module named openpyxl
        'mass_mailing_newsletter_welcome_mail',
        'mass_mailing_partner',
        'mass_mailing_unique',
        'message_auto_subscribe_notify_own',
        'website_mass_mailing_name',
        #'crm_phonecall_timesheet', needs: crm_phonecall
        'crm_timesheet',
        'hr_employee_product',
        'hr_timesheet_employee_required',
        'hr_timesheet_role',
        'hr_timesheet_sheet_role',
        'hr_timesheet_task_domain',
        'hr_timesheet_task_required',
        'hr_utilization_report',
        'sale_timesheet_line_exclude',
        'sale_timesheet_rounded',
        'sale_timesheet_task_exclude',
        'web_company_color',
        'web_decimal_numpad_dot',
        'website_legal_page',
    ],
    'data': [],
    'installable': True,
}
